[database]
dsn = "postgres://postgres.olfhzqabncwfpyjqnxix:termakan17112531!@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=disable"

# auth.config
[auth]
jwt_secret = "your_strong_secret_key123" 